"""Add multi-stage approval workflow columns

Revision ID: 400a6aa65921
Revises: 8566ae2ae4e3
Create Date: 2025-09-24 10:42:10.888114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400a6aa65921'
down_revision = '8566ae2ae4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_incharge_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('it_services_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lab_incharge_approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('it_services_approved_by', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('pending', 'guide_approved', 'lab_incharge_approved', 'hod_approved', 'it_services_approved', 'approved', 'rejected', name='statusenum'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_project_requests_it_services_approved_by', 'users', ['it_services_approved_by'], ['id'])
        batch_op.create_foreign_key('fk_project_requests_lab_incharge_approved_by', 'users', ['lab_incharge_approved_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('student', 'faculty', 'project_guide', 'lab_incharge', 'hod', 'it_services', 'admin', 'external', name='roleenum'),
               existing_nullable=False)
        batch_op.alter_column('campus',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('central_campus', 'kengeri_campus', 'yeshwanthpur_campus', 'bannerghatta_campus', 'delhi_ncr', 'pune_lavasa_campus', name='campusenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('campus',
               existing_type=sa.Enum('central_campus', 'kengeri_campus', 'yeshwanthpur_campus', 'bannerghatta_campus', 'delhi_ncr', 'pune_lavasa_campus', name='campusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('student', 'faculty', 'project_guide', 'lab_incharge', 'hod', 'it_services', 'admin', 'external', name='roleenum'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    with op.batch_alter_table('project_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_requests_it_services_approved_by', type_='foreignkey')
        batch_op.drop_constraint('fk_project_requests_lab_incharge_approved_by', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'guide_approved', 'lab_incharge_approved', 'hod_approved', 'it_services_approved', 'approved', 'rejected', name='statusenum'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
        batch_op.drop_column('it_services_approved_by')
        batch_op.drop_column('lab_incharge_approved_by')
        batch_op.drop_column('it_services_approved_at')
        batch_op.drop_column('lab_incharge_approved_at')

    # ### end Alembic commands ###
